### ISSUE TITLE
SDR Tranceiver 

### ISSUE THREAD

**Issue by haynesm1** [pavel-demin/eclypse-z7-notes#2]
Hello,

I wanted to say that this repo is awesome and has really helped me a lot to understand SDR and such. I am currently having an issue since your recent release. When I assign the board with an IP address that all goes through but when I navigate to the IP in a web browser and go to the SDR transceiver section of the webpage it loses the IP address. I am able to ping the IP of the board before I enter the transceiver program but after the host is unreachable. I am not sure if it is an error in my configuration on my end or if it is something that is closing the connection when I enter and start the program on the board. This wasn't happening in your previous releases. Any help you have would be greatly appreciated. Thank you again for the repo and the hard work you are putting into this project.

**Comment by pavel-demin** [comment]
Thank you for your kind words. I am glad that you found this repository helpful.

The last two releases ([20230222](https://github.com/pavel-demin/eclypse-z7-notes/releases/tag/20230222) and [20221217](https://github.com/pavel-demin/eclypse-z7-notes/releases/tag/20221217)) only work with the new [Zmod Digitizer](https://digilent.com/reference/zmod/digitizer/start) module.

If you use these new releases with the [Zmod Scope](https://digilent.com/reference/zmod/scope/start) module, then I think the system should completely freeze when starting the SDR transceiver application.

If this is the case, then the only solution is to continue using the previous version  ([20210404](https://github.com/pavel-demin/eclypse-z7-notes/releases/tag/20210404)).

At the moment I do not know how to make the new releases compatible with both [Zmod Digitizer](https://digilent.com/reference/zmod/digitizer/start) and [Zmod Scope](https://digilent.com/reference/zmod/scope/start).

**Comment by haynesm1** [comment]
Ok, that makes sense I am using the Digitizer module so that is why I see the freezing on my side. Thank you for the quick response.
