### ISSUE TITLE
Cross Compiling sdr-transceiver.c

### ISSUE THREAD

**Issue by haynesm1** [pavel-demin/eclypse-z7-notes#3]
Hello,

I am currently attempting to expand your repo to incorporate the second ADC on the eclypse board. My issue lies in how you compiled the C code to generate the sdr-transceiver file the is in your SD card image files. I tried to use a cross compiler but had no luck. Additionally I tried to build and run the code in Vitis to no avail. If you could provide what you used to compile your code and generate your sdr-transceiver file that would be great.

**Comment by pavel-demin** [comment]
I use the [alpine.sh](https://github.com/pavel-demin/eclypse-z7-notes/blob/master/scripts/alpine.sh) script to build the SD card image files and all the compilation is done by this script. It uses the GCC compiler provided by Alpine Linux.

I think the easiest would be to compile `sdr-transceiver.c` directly on the Eclypse Z7 board. At least, that is how I do when I need to test some changes.

The build tools can be installed with the following command:
```
apk add make gcc
```
If you prefer to keep them installed by default, then write the changes to the SD card with the following command:
```
lbu commit -d 
```
The commands to compile `sdr-transceiver.c` are
```
cd apps/sdr_tranceiver
rw
make
```

**Comment by haynesm1** [comment]
Thank you for the response! I was able to follow your steps and successfully compile the code on the board.
